# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 500)
        MainWindow.setStyleSheet("background:qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 40, 711, 401))
        self.frame.setToolTip("")
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(245, 245, 245);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 40, 391, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnDangNhap = QtWidgets.QPushButton(self.frame)
        self.btnDangNhap.setGeometry(QtCore.QRect(300, 330, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btnDangNhap.setFont(font)
        self.btnDangNhap.setMouseTracking(False)
        self.btnDangNhap.setStyleSheet("\n"
"QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/right-to-bracket-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDangNhap.setIcon(icon)
        self.btnDangNhap.setCheckable(False)
        self.btnDangNhap.setObjectName("btnDangNhap")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(250, 120, 331, 177))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("padding-left:3px;\n"
"color: red;\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("padding-left: 3px;\n"
"color: red;\n"
"")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(130, 45))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.edtTenDangNhap = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.edtTenDangNhap.setMinimumSize(QtCore.QSize(0, 0))
        self.edtTenDangNhap.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.edtTenDangNhap.setFont(font)
        self.edtTenDangNhap.setStyleSheet("border: 1px solid black;\n"
"border-radius: 5px;\n"
"background-color:white;")
        self.edtTenDangNhap.setBackgroundVisible(False)
        self.edtTenDangNhap.setCenterOnScroll(False)
        self.edtTenDangNhap.setObjectName("edtTenDangNhap")
        self.gridLayout.addWidget(self.edtTenDangNhap, 1, 1, 1, 1)
        self.edtMatKhau = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.edtMatKhau.setMinimumSize(QtCore.QSize(0, 0))
        self.edtMatKhau.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.edtMatKhau.setFont(font)
        self.edtMatKhau.setStyleSheet("border: 1px solid black;\n"
"border-radius: 5px;\n"
"background-color:white;")
        self.edtMatKhau.setBackgroundVisible(False)
        self.edtMatKhau.setCenterOnScroll(False)
        self.edtMatKhau.setObjectName("edtMatKhau")
        self.gridLayout.addWidget(self.edtMatKhau, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(630, 20, 61, 61))
        self.label_7.setToolTip("")
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("background-color:rgb(220, 220, 220)")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../images/face.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20, 380, 671, 20))
        self.label_8.setObjectName("label_8")
        self.label_7.raise_()
        self.label.raise_()
        self.btnDangNhap.raise_()
        self.gridLayoutWidget.raise_()
        self.label_8.raise_()
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 141, 141))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../images/security.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.frame.raise_()
        self.gridLayoutWidget.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phần mềm điểm danh sinh viên"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">XIN CHÀO</p><p align=\"center\"><br/></p></body></html>"))
        self.btnDangNhap.setText(_translate("MainWindow", "ĐĂNG NHẬP"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu"))
        self.label_5.setText(_translate("MainWindow", "(*)"))
        self.label_6.setText(_translate("MainWindow", "(*)"))
        self.label_2.setText(_translate("MainWindow", "Tên đăng nhập"))
        self.edtTenDangNhap.setPlaceholderText(_translate("MainWindow", "Nhập tên đăng nhập"))
        self.edtMatKhau.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.label_8.setText(_translate("MainWindow", "Lưu ý: (*) là các trường bắt buộc nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
