

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame.setStyleSheet("background-color:rgb(13, 28, 79);\n"
"QPushButton{\n"
"\n"
"background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777209))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.widget.setFont(font)
        self.widget.setStyleSheet("QPushButton{\n"
"    background-color:white;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btnTrangChu = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnTrangChu.setFont(font)
        self.btnTrangChu.setStyleSheet("background-color: white; align:left;")
        self.btnTrangChu.setObjectName("btnTrangChu")
        self.verticalLayout_2.addWidget(self.btnTrangChu)
        self.btnTrangChu.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.trangchu))
        
        self.btnSinhVien = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnSinhVien.setFont(font)
        self.btnSinhVien.setObjectName("btnSinhVien")
        self.verticalLayout_2.addWidget(self.btnSinhVien)
        self.btnSinhVien.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.sinhvien))
        
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.widget)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.horizontalLayout_2.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.trangchu = QtWidgets.QWidget()
        self.trangchu.setObjectName("trangchu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.trangchu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.trangchu)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.trangchu)
        self.sinhvien = QtWidgets.QWidget()
        self.sinhvien.setObjectName("sinhvien")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sinhvien)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.sinhvien)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.sinhvien)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QUẢN TRỊ"))
        self.btnTrangChu.setText(_translate("MainWindow", "TRANG CHỦ"))
        self.btnSinhVien.setText(_translate("MainWindow", "SINIH VIÊN"))
        self.pushButton_4.setText(_translate("MainWindow", "LỚP"))
        self.pushButton_3.setText(_translate("MainWindow", "NGÀNH"))
        self.pushButton_7.setText(_translate("MainWindow", "HỌC PHẦN"))
        self.pushButton_6.setText(_translate("MainWindow", "GIẢNG VIÊN"))
        self.label_2.setText(_translate("MainWindow", "Trang chủ"))
        self.label_3.setText(_translate("MainWindow", "Sinh viên"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)   
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
